services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: platform

    ports:
      - "3306:3306"
    networks:
      - network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - network

  admin:
    build: ./admin
    container_name: admin
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=platform
    networks:
      - network
    ports:
      - "4000:4000"

  client-streaming:
    build: ./client-steaming
    container_name: client-streaming
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=clientstreaming
    networks:
      - network
    ports:
      - "3200:3200"

  clientlient:
    build: ./clientlient
    container_name: clientlient-service
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=clientstreaming
    networks:
      - network
    ports:
      - "3001:3001"

networks:
  network:
    driver: bridge
